### PR TITLE
Fix handling of native union types containing null

### LINKED ISSUE #567: Field nullable union type is throwing an error
Having a type like this:

```php
#[Type]
class File {
	#[Field(name: 'sizes')]
	public function sizes(): ImageSizes|VideoSizes|null {}
}
```

throws an error saying `null` can't be converted to a GraphQL type. GraphQL spec does allow nullable unions, so this seems to be a bug with `graphqlite`. 

For the above function `phpDocumentor` reports the following type:
```php
new Nullable(
	realType: new Compound(
		types: [
			new Object_(),
			new Object_(),
			new Null_(),
		]
	)
)
```
so when `NullableTypeMapperAdapter` attempts to get a non-nullable version of that it goes through https://github.com/thecodingmachine/graphqlite/blob/master/src/Mappers/Root/NullableTypeMapperAdapter.php#L129
and returns the `Compound` type instance with `Null_` being one of the types.

Fix should be trivial: return `return $this->getNonNullable($type->getActualType())` instead of `return $type->getActualType()`

I can PR this change.

### PR DESCRIPTION
**Pull request by oprypkhantc**
Closes #567

TypeHandler wraps native types in `Nullable` if they allow null, even if it's a union with `null` being one of the types. I figured a fix in `NullableTypeMapper` would be needed anyway, in case someone wrongfully does the same, and haven't touched the `TypeHandler` to avoid recursively iterating through types in it.

### CODE REVIEW

**Comment by oprypkhantc** [comment]
By the way, code is not formatted correctly because phpcs still fixes way too much files for this small PR, and there's no GitHub action workflow for it. 

I'll add a github workflow and fix the codestyle in a separate PR, so let's hold this before codestyle is merged

**Comment by oprypkhantc** [comment]
@oojacoboo Nevermind, I can't get `phpcs --tab-width=4` to work, even though it's officially supported and is in the docs, it still doesn't replace tabs with spaces.

What do you think of [php-cs-fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer)? It's very similar to php codesniffer but at least it fixes tabbing. It has a ton of fixers with a lot of configuration and ready rule sets - for PSR2, PSR12, Symfony and Doctrine annotations. It's also the one used by `symfony/symfony`.

If you don't mind, I can PR php-cs-fixer improvement as well. It's mostly plug-n-play.

**Comment by oojacoboo** [comment]
@oprypkhantc thanks for this.  

On `php-cs-fixer`, it can be a great tool.  I haven't dug into the phpcs configuration with this repo much.  Can't you just use `php-cs-fixer` on the `phpcs.xml.dist` config?  I don't see any reason to add the dependency to the repo when the tool can be used as needed by the developer.

File: src/Mappers/Root/NullableTypeMapperAdapter.php [hunk 1]
```diff
@@ -126,7 +126,7 @@ private function getNonNullable(Type $type): Type|null
             return null;
         }
         if ($type instanceof Nullable) {
-            return $type->getActualType();
+            return $this->getNonNullable($type->getActualType());
```
Comment (oojacoboo) [inline src/Mappers/Root/NullableTypeMapperAdapter.php:129]: Does this read weird, or am I missing something here?

If $type is an instance of nullable, get non-nullable?

**Comment by oprypkhantc** [comment]
@oojacoboo `php-cs-fixer` can't be used with `phpcs`'s config, unfortunately. They have their own format with their own set of fixers & configuration.

Right now the code style is not enforced in any way - it's skipped in the Github workflow, so anything can be mistakenly merged with an invalid codestyle. Having a consistent fixer/checker would be nice for newcomers like me who are used to different codestyle.

I'll PR a change of `phpcs` to `php-cs-fixer` then, if you don't like - feel free to decline it.

**Review by oojacoboo — APPROVED** [review]
